### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sssan-tech** [sssan-tech/furima-41472#20]
#URL
https://furima-41472.onrender.com/

---

本番環境下での動作確認をお願いできますでしょうか？
Basic認証のユーザー名とパスワードは実装条件の通り自分で任意のものを設定しております。

どうぞよろしくお願いいたします。

**Comment by motomuun** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、1点だけ修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **発送元の地域は、「---」と47都道府県の合計48項目が表示されること（--- は初期値として設定すること）**
 初期値が「--」になっています。要件と揃えて「---」となるように修正しましょう。
<img width="377" alt="スクリーンショット 2024-12-10 10 06 31" src="https://github.com/user-attachments/assets/15e6d080-ca56-4249-aec1-be717b27331c">



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sssan-tech** [comment]
早々のご確認とご指摘をありがとうございます。
ご指摘いただいた初期値の修正が完了しましたので、再度完了フォームを提出いたします。

再度お手数ですが、ご確認のほどどうぞよろしくお願いいたします。

※初回提出時以外でデータベースの初期化は行っておりませんので、
　動作確認時に作成いただいたデータはそのままの状態での再鑑依頼となっております。

**Comment by motomuun** [comment]
最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by sssan-tech** [comment]
上記LGTMをありがとうございます！
実装作業中含め何度もコードの確認、修正のご指摘・アドバイスをいただきありがとうござました。

一連の実装を通して、まだまだ身についていないスキルなどが実感できました。
オリジナルアプリ作成に取り組む前に今一度復習や、さらなる知識獲得の時間を設けたいと思います。

引き続き何卒よろしくお願い申し上げます。
